use proc_macro2::{Ident, Span, TokenStream};
use quote::{format_ident, quote};
use std::collections::BTreeMap;
use syn::DeriveInput;

use crate::{input::SelectionKind, path, selection};

#[derive(Debug, Clone, Copy)]
pub enum EnumKind {
    Fields,
    Sort,
}

#[derive(Debug, Clone, Copy)]
pub struct EnumConfig {
    pub derive_name: &'static str,
    pub enum_suffix: &'static str,
    pub nested_enum_suffix: &'static str,
    pub include_by_default: bool,
    pub nested_value: NestedValue,
    pub selection_kind: SelectionKind,
    pub include_sort_extras: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NestedValue {
    One,
    Flat,
}

impl NestedValue {
    pub fn emits_nested_payload(self) -> bool {
        !matches!(self, Self::Flat)
    }
}

impl EnumKind {
    fn config(self) -> EnumConfig {
        match self {
            Self::Fields => EnumConfig {
                derive_name: "VndbFieldsEnum",
                enum_suffix: "Fields",
                nested_enum_suffix: "Fields",
                include_by_default: true,
                nested_value: NestedValue::One,
                selection_kind: SelectionKind::Field,
                include_sort_extras: false,
            },
            Self::Sort => EnumConfig {
                derive_name: "VndbSortEnum",
                enum_suffix: "Sort",
                nested_enum_suffix: "Filters",
                include_by_default: false,
                nested_value: NestedValue::Flat,
                selection_kind: SelectionKind::Sort,
                include_sort_extras: true,
            },
        }
    }
}

pub fn derive_enum(input: DeriveInput, kind: EnumKind) -> TokenStream {
    let config = kind.config();

    match expand_enum(&input, config) {
        Ok(expanded) => expanded,
        Err(error) => error.to_compile_error(),
    }
}

fn expand_enum(input: &DeriveInput, config: EnumConfig) -> syn::Result<TokenStream> {
    let enum_ident = suffixed_ident(&input.ident, config.enum_suffix);
    let selections = selection::fields::collect(input, config)?;

    let variant_defs = selections.iter().map(|selection| {
        let variant_ident = &selection.variant_ident;

        if selection.flattened {
            let nested_enum_ident = selection
                .nested_enum_ident
                .as_ref()
                .expect("flattened selections must have a child enum");
            let payload_ty = nested_payload_ty(selection, nested_enum_ident);

            return quote! {
                #variant_ident(#payload_ty)
            };
        }

        match &selection.nested_enum_ident {
            Some(nested_enum_ident) => match config.nested_value {
                NestedValue::One => {
                    let payload_ty = nested_payload_ty(selection, nested_enum_ident);

                    quote! {
                        #variant_ident(#payload_ty)
                    }
                }
                NestedValue::Flat => quote! {
                    #variant_ident
                },
            },
            None => quote! {
                #variant_ident
            },
        }
    });

    let selector_arms = selections.iter().map(|selection| {
        let variant_ident = &selection.variant_ident;
        let path = &selection.path;

        if selection.flattened {
            return quote! {
                Self::#variant_ident(item) => {
                    ::vndb_api_macros_support::selector::VndbSelector::selector(item)
                }
            };
        }

        match (&selection.nested_enum_ident, config.nested_value) {
            (Some(_), NestedValue::One) => quote! {
                Self::#variant_ident(item) => {
                    let mut selector = ::std::string::String::from(#path);
                    selector.push('{');
                    selector.push_str(
                        &::vndb_api_macros_support::selector::VndbSelector::selector(item),
                    );
                    selector.push('}');
                    selector
                }
            },
            (Some(_), NestedValue::Flat) => quote! {
                Self::#variant_ident => ::std::string::String::from(#path)
            },
            (None, _) => quote! {
                Self::#variant_ident => ::std::string::String::from(#path)
            },
        }
    });

    let flattened_from_impls = flattened_from_impls(&enum_ident, &selections);
    let field_helpers = field_helpers(&enum_ident, &selections, config);
    let path_helpers = path::helpers(
        &enum_ident,
        &input.vis,
        &selections,
        path::PathConfig {
            derive_name: config.derive_name,
        },
    );
    let doc = format!("Auto-generated by `#[derive({})]`.", config.derive_name);

    Ok(quote! {
        #[doc = #doc]
        #[allow(dead_code)]
        #[derive(Debug, Clone)]
        pub enum #enum_ident {
            #( #variant_defs, )*
        }

        impl serde::Serialize for #enum_ident {
            fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
            where
                S: serde::Serializer
            {
                serializer.serialize_str(
                    &::vndb_api_macros_support::selector::VndbSelector::selector(self)
                )
            }
        }

        impl ::vndb_api_macros_support::selector::VndbSelector for #enum_ident {
            fn selector(&self) -> ::std::string::String {
                match self {
                    #( #selector_arms, )*
                }
            }
        }

        impl std::fmt::Display for #enum_ident {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str(
                    &::vndb_api_macros_support::selector::VndbSelector::selector(self)
                )
            }
        }

        #( #flattened_from_impls )*

        #field_helpers

        #path_helpers
    })
}

fn suffixed_ident(ident: &Ident, suffix: &str) -> Ident {
    format_ident!("{}{}", ident, suffix, span = ident.span())
}

fn nested_payload_ty(selection: &selection::Selection, nested_enum_ident: &Ident) -> TokenStream {
    if selection.nested_boxed {
        quote! { std::boxed::Box<#nested_enum_ident> }
    } else {
        quote! { #nested_enum_ident }
    }
}

pub(crate) fn flattened_from_impls(
    enum_ident: &Ident,
    selections: &[selection::Selection],
) -> Vec<TokenStream> {
    let mut child_counts = BTreeMap::<String, usize>::new();

    for selection in selections.iter().filter(|selection| selection.flattened) {
        if let Some(nested_enum_ident) = &selection.nested_enum_ident {
            *child_counts
                .entry(nested_enum_ident.to_string())
                .or_default() += 1;
        }
    }

    selections
        .iter()
        .filter(|selection| selection.flattened)
        .filter_map(|selection| {
            let variant_ident = &selection.variant_ident;
            let nested_enum_ident = selection.nested_enum_ident.as_ref()?;
            let wrapped_item = if selection.nested_boxed {
                quote! { std::boxed::Box::new(item) }
            } else {
                quote! { item }
            };

            if child_counts.get(&nested_enum_ident.to_string()) != Some(&1) {
                return None;
            }

            Some(quote! {
                impl std::convert::From<#nested_enum_ident> for #enum_ident {
                    fn from(item: #nested_enum_ident) -> Self {
                        Self::#variant_ident(#wrapped_item)
                    }
                }
            })
        })
        .collect()
}

fn field_helpers(
    enum_ident: &Ident,
    selections: &[selection::Selection],
    config: EnumConfig,
) -> TokenStream {
    if config.derive_name != "VndbFieldsEnum" {
        return quote! {};
    }

    let constructors = selections.iter().map(field_constructor);
    let all_non_recursive_arms = selections.iter().map(field_all_non_recursive_arm);
    let enum_name = enum_ident.to_string();

    quote! {
        impl #enum_ident {
            #( #constructors )*

            pub fn all() -> ::std::vec::Vec<Self> {
                Self::__vndb_all_non_recursive(&mut ::std::vec::Vec::new())
            }

            #[doc(hidden)]
            pub fn __vndb_all_non_recursive(active: &mut ::std::vec::Vec<&'static str>) -> ::std::vec::Vec<Self> {
                if active.contains(&#enum_name) {
                    return ::std::vec::Vec::new();
                }

                active.push(#enum_name);

                let mut items = ::std::vec::Vec::new();
                #( #all_non_recursive_arms )*

                active.pop();
                items
            }
        }
    }
}

fn field_constructor(selection: &selection::Selection) -> TokenStream {
    let variant_ident = &selection.variant_ident;
    let method_ident = field_method_ident(&selection.path, variant_ident.span());

    match &selection.nested_enum_ident {
        Some(nested_enum_ident) => {
            let wrap_item = wrapped_nested_item(selection);

            quote! {
                pub fn #method_ident(item: #nested_enum_ident) -> Self {
                    Self::#variant_ident(#wrap_item)
                }
            }
        }
        None => quote! {
            pub fn #method_ident() -> Self {
                Self::#variant_ident
            }
        },
    }
}

fn field_all_non_recursive_arm(selection: &selection::Selection) -> TokenStream {
    let variant_ident = &selection.variant_ident;

    match &selection.nested_enum_ident {
        Some(nested_enum_ident) => {
            let wrap_item = wrapped_nested_item(selection);

            quote! {
                for item in #nested_enum_ident::__vndb_all_non_recursive(active) {
                    items.push(Self::#variant_ident(#wrap_item));
                }
            }
        }
        None => quote! {
            items.push(Self::#variant_ident);
        },
    }
}

fn wrapped_nested_item(selection: &selection::Selection) -> TokenStream {
    if selection.nested_boxed {
        quote! { ::std::boxed::Box::new(item) }
    } else {
        quote! { item }
    }
}

fn field_method_ident(path: &str, span: Span) -> Ident {
    if is_rust_keyword(path) {
        Ident::new_raw(path, span)
    } else {
        Ident::new(path, span)
    }
}

fn is_rust_keyword(ident: &str) -> bool {
    matches!(
        ident,
        "as" | "async"
            | "await"
            | "break"
            | "const"
            | "continue"
            | "crate"
            | "dyn"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "abstract"
            | "become"
            | "box"
            | "do"
            | "final"
            | "macro"
            | "override"
            | "priv"
            | "try"
            | "typeof"
            | "unsized"
            | "virtual"
            | "yield"
    )
}
