[package]
name = "vndb-api"
version = "0.1.0"
edition = "2021"

[lib]
name = "vndb_api"
path = "src/lib.rs"


[dependencies]
reqwest = { "version" = "0.12.23", "features" = ["json"] }
serde_json = "1"
serde = "1"
vndb-api-derive = { path = "../vndb-api-derive" }